//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorsTotalReport {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=..\\..\\..\\..\\Resources\\supermarket-database.db;Version=3;Pooling=False" +
            ";Max Pool Size=100")]
        public string SqLiteConnectionString {
            get {
                return ((string)(this["SqLiteConnectionString"]));
            }
            set {
                this["SqLiteConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost/")]
        public string MongoConnectionString {
            get {
                return ((string)(this["MongoConnectionString"]));
            }
            set {
                this["MongoConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SupermarketDatabase")]
        public string MongoDatabaseName {
            get {
                return ((string)(this["MongoDatabaseName"]));
            }
            set {
                this["MongoDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProductsReports")]
        public string MongoCollectionName {
            get {
                return ((string)(this["MongoCollectionName"]));
            }
            set {
                this["MongoCollectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProductReports")]
        public string SqliteTableName {
            get {
                return ((string)(this["SqliteTableName"]));
            }
            set {
                this["SqliteTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VendorExpenses")]
        public string MongoVendorCollectionName {
            get {
                return ((string)(this["MongoVendorCollectionName"]));
            }
            set {
                this["MongoVendorCollectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Resources\\Excel.bin")]
        public string ExcelBinTemplate {
            get {
                return ((string)(this["ExcelBinTemplate"]));
            }
            set {
                this["ExcelBinTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Resources\\Vendors-Total-Report.xlsx")]
        public string ReportFileName {
            get {
                return ((string)(this["ReportFileName"]));
            }
            set {
                this["ReportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=..\\..\\..\\..\\Resources\\Vendors-Total" +
            "-Report.xlsx;Extended Properties=\"Excel 12.0;HDR=YES;\"")]
        public string ExcelConnectionString {
            get {
                return ((string)(this["ExcelConnectionString"]));
            }
            set {
                this["ExcelConnectionString"] = value;
            }
        }
    }
}
